repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v2.3.0
    hooks:
      - id: check-yaml
      - id: end-of-file-fixer
      - id: trailing-whitespace
      - id: pretty-format-json
        args: ["--autofix"]
      - id: detect-private-key
      - id: requirements-txt-fixer
      - id: sort-simple-yaml

  - repo: https://github.com/sqlfluff/sqlfluff
    rev: 1.3.2
    hooks:
      - id: sqlfluff-lint
      - id: sqlfluff-fix

  - repo: https://github.com/psf/black
    rev: 22.10.0
    hooks:
      - id: black
        language_version: python3.10
        args: ["--line-length=88"]

  - repo: https://github.com/PyCQA/pydocstyle
    rev: 6.1.1
    hooks:
      - id: pydocstyle
        language_version: python3.10

  - repo: https://github.com/PyCQA/isort
    rev: 5.12.0
    hooks:
      - id: isort
        args: ["--profile", "black"]
        language_version: python3.10

  - repo: https://github.com/PyCQA/flake8
    rev: 5.0.4
    hooks:
      - id: flake8
        language_version: python3.10

  - repo: https://github.com/pre-commit/pygrep-hooks
    rev: v1.9.0
    hooks:
      - id: python-check-blanket-noqa
      - id: python-check-blanket-type-ignore
      - id: python-use-type-annotations
      - id: python-no-eval
      - id: python-check-mock-methods

  - repo: local
    hooks:
      - id: pytest-check
        name: pytest-check
        # Execute from virtualenv
        # Exclude end_to_end tests
        entry: .venv/bin/pytest -m 'not end_to_end'
        language: system
        pass_filenames: false
        always_run: true
